version: "3.8"
services:
  nginx:
    image: httpd:latest
    ports:
      - 80:80
    deploy:
      replicas: 1
      placement:
        constraints: 
           - node.labels.nodeType == monitor
          # - node.role == worker
