version: '3'
services:
  elasticsearch:
    image: elasticsearch:8.7.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ELASTIC_PASSWORD: 'tudip123'
    volumes:
      - ./kibana-data:/usr/share/elasticsearch/data
    # mem_limit: "1g"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.23.76.199:12201"
        tag: "elasticsearch-app"

  kibana:
    image: kibana:8.7.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.23.76.199:12201"
        tag: "kibana-app"
  
  logstash-central:
    image: logstash:8.7.1
    volumes:
      - ./logstash-central:/etc/logstash
    command: logstash -f /etc/logstash/logstash.conf
    ports:
      - 12201:12201/udp
    depends_on:
      - elasticsearch
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.23.76.199:12201"
        tag: "logstash-app"